spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: http://192.168.113.129:9411
  boot:
    admin:
      client:
        url: http://192.168.113.129:8084

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.113.129
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info