spring:
  application:
    name: itoken-service-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
      druid:
        url: jdbc:mysql://localhost:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true
        # MySQL 8.x: com.mysql.cj.jdbc.Driver
        driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

mybatis:
    type-aliases-package: itoken.service.admin.domain
    mapper-locations: classpath:mapper/*.xml

