spring:
  application:
    name: itoken-service-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/itoken-service-admin?characterEncoding=utf8
      username: root
      password: root

server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

mybatis:
    type-aliases-package: itoken.service.admin.domain
    mapper-locations: classpath:mapper/*.xml

